//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::FacilitiesStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "facilities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub facility_type: Option<String>,
    pub images: Option<Vec<String>>,
    #[sea_orm(unique)]
    pub license_number: String,
    pub country_code: Option<String>,
    pub phone_number: Option<String>,
    pub email: Option<String>,
    pub website: Option<String>,
    pub address: String,
    pub city: String,
    pub county: String,
    pub country: String,
    pub postal_code: String,
    #[sea_orm(column_type = "Decimal(Some((10, 8)))")]
    pub latitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((11, 8)))")]
    pub longitude: Decimal,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub operating_hours: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub rating: Decimal,
    pub total_reviews: i32,
    pub status: FacilitiesStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub is_main_branch: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub facility_reviews: HasMany<super::facility_reviews::Entity>,
    #[sea_orm(has_many)]
    pub facility_services: HasMany<super::facility_services::Entity>,
    #[sea_orm(has_many)]
    pub facility_staffs: HasMany<super::facility_staff::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
