//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod facilities;
pub mod facility_reviews;
pub mod facility_services;
pub mod facility_staff;
pub mod sea_orm_active_enums;
pub mod service_categories;
pub mod service_reviews;
pub mod services;
pub mod users;
