//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub use super::facilities::Entity as Facilities;
pub use super::facility_reviews::Entity as FacilityReviews;
pub use super::facility_services::Entity as FacilityServices;
pub use super::facility_staff::Entity as FacilityStaff;
pub use super::service_categories::Entity as ServiceCategories;
pub use super::service_reviews::Entity as ServiceReviews;
pub use super::services::Entity as Services;
pub use super::users::Entity as Users;
