//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "services")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub price: Option<i32>,
    pub duration: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub rating: Decimal,
    pub total_reviews: i32,
    pub icon: Option<String>,
    pub features: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub facility_services: HasMany<super::facility_services::Entity>,
    #[sea_orm(has_many)]
    pub service_reviews: HasMany<super::service_reviews::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
