//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "service_reviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub service_id: i32,
    pub sso_user_id: Uuid,
    pub rating: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "service_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub services: HasOne<super::services::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
