//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::Gender;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub sso_user_id: Uuid,
    pub photo_url: Option<String>,
    pub dob: Option<Date>,
    pub gender: Option<Gender>,
    #[sea_orm(unique)]
    pub license_number: Option<String>,
    pub specialization: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub city: Option<String>,
    pub county: Option<String>,
    pub country: Option<String>,
    pub postal_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub emergency_contact: Option<Json>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub facility_staffs: HasMany<super::facility_staff::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
