//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::BillingItemType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "billing_line_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub tenant_id: i32,
    pub subscription_id: i32,
    pub billing_period_start: Date,
    pub billing_period_end: Date,
    pub item_type: BillingItemType,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_amount: Decimal,
    pub metadata: Option<Json>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "subscription_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub subscriptions: HasOne<super::subscriptions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
