//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_flags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub flag_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_enabled_globally: bool,
    pub rollout_percentage: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub target_tiers: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub target_tenants: Option<Json>,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
