//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "global_system_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    #[sea_orm(unique)]
    pub sso_user_id: Option<Uuid>,
    pub tenant_id: Option<i32>,
    pub source: String,
    pub ip_address: String,
    pub status_code: i32,
    pub request_url: String,
    pub method: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
