//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::InsuranceDependentRelationship;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "insurance_dependents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub insurance_id: i32,
    pub dependent_patient_id: i32,
    pub relationship: Option<InsuranceDependentRelationship>,
    #[sea_orm(column_type = "Text", nullable)]
    pub coverage_details: Option<String>,
    pub is_active: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "insurance_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub patient_insurance: HasOne<super::patient_insurance::Entity>,
    #[sea_orm(
        belongs_to,
        from = "dependent_patient_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub patients: HasOne<super::patients::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
