//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "insurance_providers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub name: String,
    pub email: Option<String>,
    pub country_code: Option<String>,
    pub phone_number: Option<String>,
    pub website: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_endpoint: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub api_credentials: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub supported_plans: Option<Json>,
    pub logo_url: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub patient_insurances: HasMany<super::patient_insurance::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
