//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod features;
pub mod patient_access_permissions;
pub mod patients;
pub mod sea_orm_active_enums;
pub mod subscription_plan_features;
pub mod subscription_plans;
pub mod tenant_features;
pub mod tenant_subscriptions;
pub mod tenants;
