//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::PatientBillingCycle;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patient_billing")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub patient_id: i32,
    pub billing_cycle: PatientBillingCycle,
    pub preferred_payment_method: Option<String>,
    pub auto_payment_enabled: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "patient_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub patients: HasOne<super::patients::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
