//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patient_insurance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub patient_id: i32,
    pub provider: String,
    pub policy_number: String,
    pub group_number: Option<String>,
    pub plan_type: Option<String>,
    pub coverage_start_date: Option<Date>,
    pub coverage_end_date: Option<Date>,
    pub is_primary: bool,
    pub insurance_card_front: Option<String>,
    pub insurance_card_back: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "patient_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub patients: HasOne<super::patients::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
