//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::PolicyholderRelationship;
use super::sea_orm_active_enums::VerificationStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patient_insurance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub patient_id: i32,
    pub insurance_id: i32,
    pub policy_number: String,
    pub group_number: Option<String>,
    pub plan_name: Option<String>,
    pub plan_type: Option<String>,
    pub coverage_start_date: Option<Date>,
    pub coverage_end_date: Option<Date>,
    pub policy_holder_name: Option<String>,
    pub policy_holder_relationship: Option<PolicyholderRelationship>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub copay_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub deductible_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub deductible_met_ytd: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub out_of_pocket_max: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub out_of_pocket_met_ytd: Decimal,
    pub verification_status: VerificationStatus,
    pub verified_at: Option<DateTime>,
    pub is_primary: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub card_front_image: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub card_back_image: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub insurance_dependents: HasMany<super::insurance_dependents::Entity>,
    #[sea_orm(
        belongs_to,
        from = "insurance_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub insurance_providers: HasOne<super::insurance_providers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "patient_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub patients: HasOne<super::patients::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
