//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::SubscriptionStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub tenant_id: i32,
    pub plan_id: i32,
    pub pending_plan_id: Option<i32>,
    pub status: SubscriptionStatus,
    pub current_period_start: Option<DateTime>,
    pub current_period_end: Option<DateTime>,
    pub cancel_at_period_end: bool,
    pub cancelled_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cancellation_reason: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub custom_price: Option<Decimal>,
    pub trial_days: Option<i32>,
    pub max_facilities: Option<i32>,
    pub max_users: Option<i32>,
    pub max_patients_per_month: Option<i32>,
    pub storage_gb: Option<i32>,
    pub api_rate_limit_per_hour: Option<i32>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub billing_line_items: HasMany<super::billing_line_items::Entity>,
    #[sea_orm(has_many)]
    pub payment_transactions: HasMany<super::payment_transactions::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "SubscriptionPlans2",
        from = "pending_plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub subscription_plans_2: HasOne<super::subscription_plans::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "SubscriptionPlans1",
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub subscription_plans_1: HasOne<super::subscription_plans::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
