//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::BillingCycle;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscription_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_weekly: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_monthly: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_quartely: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_yearly: Option<Decimal>,
    pub trial_days: i32,
    pub max_facilities: Option<i32>,
    pub max_users: Option<i32>,
    pub max_patients_per_month: Option<i32>,
    pub storage_gb: Option<i32>,
    pub api_rate_limit_per_hour: Option<i32>,
    pub billing_cycle: BillingCycle,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub setup_fee: Decimal,
    pub is_public: bool,
    pub is_active: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub subscription_plan_features: HasMany<super::subscription_plan_features::Entity>,
    #[sea_orm(has_many)]
    pub subscriptions: HasMany<super::subscriptions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
