//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::SubscriptionPlansBillingCycle;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscription_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub price: Decimal,
    pub billing_cycle: SubscriptionPlansBillingCycle,
    pub max_pharmacies: i32,
    pub max_users: i32,
    pub is_active: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub subscription_plan_features: HasMany<super::subscription_plan_features::Entity>,
    #[sea_orm(has_many)]
    pub tenant_subscriptions: HasMany<super::tenant_subscriptions::Entity>,
    #[sea_orm(has_many)]
    pub tenants: HasMany<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
