//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::TenantSubscriptionsStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_subscriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub tenant_id: i32,
    pub plan_id: i32,
    pub status: TenantSubscriptionsStatus,
    pub custom_price: Option<Decimal>,
    pub max_pharmacies: Option<i32>,
    pub max_users: Option<i32>,
    pub current_period_start: DateTime,
    pub current_period_end: DateTime,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub subscription_plans: HasOne<super::subscription_plans::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
