//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub sso_tenant_id: Option<Uuid>,
    pub db_url: String,
    pub plan_id: i32,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub subscription_plans: HasOne<super::subscription_plans::Entity>,
    #[sea_orm(has_many)]
    pub tenant_features: HasMany<super::tenant_features::Entity>,
    #[sea_orm(has_many)]
    pub tenant_subscriptions: HasMany<super::tenant_subscriptions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
