//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::SubscriptionTier;
use super::sea_orm_active_enums::TenantSubscriptionStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub sso_tenant_id: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(unique)]
    pub db_name: String,
    pub db_username: Option<String>,
    pub db_password: Option<String>,
    pub subscription_tier: Option<SubscriptionTier>,
    pub subscription_status: TenantSubscriptionStatus,
    pub trial_ends_at: Option<DateTime>,
    pub subscription_started_at: Option<DateTime>,
    pub subscription_ends_at: Option<DateTime>,
    pub contact_email: Option<String>,
    pub contact_phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub logo_url: Option<String>,
    pub timezone: String,
    pub currency: String,
    pub settings: Option<Json>,
    pub onboarding_completed: bool,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub billing_line_items: HasMany<super::billing_line_items::Entity>,
    #[sea_orm(has_many)]
    pub feature_usage_logs: HasMany<super::feature_usage_logs::Entity>,
    #[sea_orm(has_many)]
    pub global_system_logs: HasMany<super::global_system_logs::Entity>,
    #[sea_orm(has_many)]
    pub payment_transactions: HasMany<super::payment_transactions::Entity>,
    #[sea_orm(has_many)]
    pub subscriptions: HasMany<super::subscriptions::Entity>,
    #[sea_orm(has_many)]
    pub tenant_features: HasMany<super::tenant_features::Entity>,
    #[sea_orm(has_many)]
    pub usage_metrics: HasMany<super::usage_metrics::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
