//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::AggregationPeriod;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "usage_metrics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub tenant_id: Option<i32>,
    pub metric_type: String,
    pub metric_value: i64,
    pub aggregation_period: AggregationPeriod,
    pub period_start: DateTime,
    pub period_end: DateTime,
    pub facility_id: Option<Uuid>,
    pub metadata: Option<Json>,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
